[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.79.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

# from https://drmowinckels.io/blog/2020-05-25-changing-you-blogdown-workflow/ to fix css issue
# blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource
# [[headers]]
#  for = "/*"
#  [headers.values]
#    Access-Control-Allow-Origin = "*"
