---
title: A Trial Post
author: John Goldin
date: '2020-06-27'
description: "spf13-vim is a cross platform distribution of vim plugins and resources" 
summary: "This is a test post used to explore some features of Hugo and how they relate to my blog posts."
excerpt: "This is just a test post."
categories:
  - Flickr
  - GPS
tags:
  - maps
subtitle: ''
draft: yes
image: ''
# draft: no
output:
  blogdown::html_page:
    toc: no
    fig_width: 5
    fig_height: 5
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, out.width = "100%",
                      knitr.table.format = "html")
# knitr.table.format is for kable. Needed this to get blogdown table to format correctly.
```
```{r libraries, message = FALSE, warning = FALSE, echo = FALSE}
# <!--more-->

library(tidyverse, quietly = TRUE)
library(lubridate, quietly = TRUE)
# library(knitr, quietly = TRUE)
library(scales, quietly = TRUE)
# library(kableExtra, quietly = TRUE)
library(gt, quietly = TRUE)
```

A relative link: [here](/img/for_site/UR_a_joke.png)

## Latest Connecticut Data from the Department of Public Health

```{r `load_basic_data`, echo = FALSE, message = FALSE}
path_to_post <- "~/Dropbox/Programming/R_Stuff/can_i_blog_too/content/post/2020-03-29-covid19-cases-in-connecticut/"
path_to_static_for_this_post <- "~/Dropbox/Programming/R_Stuff/can_i_blog_too/static/post/2020-06-19-tracking-covid-19-in-connecticut"
path_to_ctcorona <- "~/Documents/R_local_repos/ctcorona/data/"
path_to_ctcorona_r <- "~/Documents/R_local_repos/ctcorona/R/" 
load(paste0(path_to_ctcorona, "dph_datasets.RData")) 
```
```{r box-score, echo = FALSE}
#<!--more-->
recent_date <- max(dph_total$date, na.rm = TRUE)
week_ago <- recent_date - days(7)
if (!(week_ago %in% dph_total$date)) week_ago <- NA
yesterday <- recent_date - days(1) 
# if (!(yesterday %in% dph_total$date)) yesterday <- NA
# if (is.na(yesterday) || (length(dph_total$deaths[dph_total$date == yesterday]))) {
#   yesterday_deaths <- ""
# } else {yesterday_deaths <- dph_total$deaths[dph_total$date == recent_date] - dph_total$deaths[dph_total$date == yesterday]}
today_cases <- dph_total %>% filter(date == recent_date) %>% 
  select(cases) %>% pluck(1, .default = NA)
yesterday_cases <- today_cases - dph_total %>% filter(date == yesterday) %>% 
  select(cases) %>% pluck(1, .default = NA) 
week_ago_cases <-  today_cases - dph_total %>% filter(date == week_ago) %>% 
  select(cases) %>% pluck(1, .default = NA)
today_deaths <- dph_total %>% filter(date == recent_date) %>% 
  select(deaths) %>% pluck(1, .default = NA)
yesterday_deaths <- today_deaths - dph_total %>% filter(date == yesterday) %>% 
  select(deaths) %>% pluck(1, .default = NA)
week_ago_deaths <-  today_deaths - dph_total %>% filter(date == week_ago) %>% 
  select(deaths) %>% pluck(1, .default = NA)
today_hospital <- dph_total %>% filter(date == recent_date) %>% 
  select(hospital) %>% pluck(1, .default = NA)
yesterday_hospital <- today_hospital - dph_total %>% filter(date == yesterday) %>% 
  select(hospital) %>% pluck(1, .default = NA)
week_ago_hospital <-  today_hospital - dph_total %>% filter(date == week_ago) %>% 
  select(hospital) %>% pluck(1, .default = NA)
today_tests <- dph_total %>% filter(date == recent_date) %>% select(tests) %>% pluck(1, .default = NA)
yesterday_tests <- today_tests - dph_total %>% filter(date == yesterday) %>% select(tests) %>% pluck(1, .default = NA)
week_ago_tests <-  today_tests - dph_total %>% filter(date == week_ago) %>% select(tests) %>% pluck(1, .default = NA)
test_rate_day <- ((dph_total %>% filter(date == recent_date) %>% 
                 select(confirmedcases) %>% pluck(1, .default = NA)) -
                (dph_total %>% filter(date == yesterday) %>% 
                   select(confirmedcases) %>% pluck(1, .default = NA))) / 
  ((dph_total %>% filter(date == recent_date) %>% 
      select(tests) %>% pluck(1, .default = NA)) -
     (dph_total %>% filter(date == yesterday) %>%
        select(tests) %>% pluck(1, .default = NA))) 
test_rate_week <- ((dph_total %>% filter(date == recent_date) %>% 
                 select(confirmedcases) %>% pluck(1, .default = NA)) -
                (dph_total %>% filter(date == week_ago) %>% 
                   select(confirmedcases) %>% pluck(1, .default = NA))) / 
  ((dph_total %>% filter(date == recent_date) %>% 
      select(tests) %>% pluck(1, .default = NA)) -
     (dph_total %>% filter(date == week_ago) %>% 
        select(tests) %>% pluck(1, .default = NA)))
# next two versions don't deal with confirmed cases only
test_rate_day2 <- yesterday_cases / yesterday_tests
test_rate_week2 <- week_ago_cases / week_ago_tests
recent_nursing_date <- max(dph_nursing_cases$date, na.rm = TRUE)
nursing_previous_date <- dph_nursing_cases %>% select(date) %>% arrange(desc(date)) %>% unique()
nursing_previous_date <- nursing_previous_date$date[2]
nursing_hm_cases <- dph_nursing_cases %>% filter(date == recent_nursing_date) %>% 
  select(nh_cases) %>% pluck(1, .default = NA) %>% sum(na.rm = TRUE)
nh_previous_cases <-  nursing_hm_cases - dph_nursing_cases %>% filter(date == nursing_previous_date) %>% 
  select(nh_cases) %>% pluck(1, .default = NA) %>% sum(na.rm = TRUE) 
nursing_hm_deaths <- dph_nursing_cases %>% filter(date == recent_nursing_date) %>% 
  select(nh_deaths) %>% pluck(1, .default = NA) %>% sum(na.rm = TRUE)  
nh_previous_deaths <-  nursing_hm_deaths - dph_nursing_cases %>% filter(date == nursing_previous_date) %>% 
  select(nh_deaths) %>% pluck(1, .default = NA) %>% sum(na.rm = TRUE)
# use: sprintf("%+3d %%", x)
box_fmt <- function(x) {
  case_when( 
    (is.na(x) | is.null(x) | (length(x) == 0)) ~ " ",
    x < 0 ~ scales::comma(x),
    x > 0 ~ scales::comma(x, prefix = "+"),
    TRUE ~  "0"
  )
}

###########################################################################
# Box score comes here:
box_score <- tribble( 
  ~`Connecticut Covid-19`, ~`today`, ~`yesterday`, ~`week ago`,
  "Cases", today_cases, yesterday_cases, week_ago_cases,
  "Deaths", today_deaths, yesterday_deaths, week_ago_deaths,
  "Currently in Hospital", today_hospital, yesterday_hospital, week_ago_hospital,
  "Tests",    today_tests, yesterday_tests, week_ago_tests,
  " ", NA , NA_real_, NA,
  "Nursing home cases", nursing_hm_cases, NA, nh_previous_cases, 
  "Nursing home deaths", nursing_hm_deaths, NA, nh_previous_deaths 
) %>% 
   mutate( yesterday = map_chr(yesterday, box_fmt),
         `week ago` = map_chr(`week ago`, box_fmt), today = ifelse(is.na(today), "", scales::comma(today))) 
```

```{r format-box-score-table, echo = FALSE}
# columns for box scores:
# town, category, population, cases, cases per 100K, recent cases per 100K, percent positive tests
# deaths, percent of deaths in nh, 
box_score %>%
  tibble::add_row(`Connecticut Covid-19` = "Rate of positive tests", 
                  today = "", 
                  yesterday = paste0(round(test_rate_day * 100, 1.1), "%"), `week ago` = paste0(round(test_rate_week * 100, 1.1), "%"), .after = 4) %>% 
  gt() %>% 
  tab_header(title = "Latest Data on Covid-19 in Connecticut",
             # subtitle = md(paste0('Should correspond to [', dph_reports$name[1],
             #                      '](', dph_reports$url[1], ') from the Department of Public Health'))) %>% 
             subtitle = md(paste("Data as of ", format(max(dph_counties$date, na.rm = TRUE), "%B %d, %Y")))) %>% 
  cols_label(
    `Connecticut Covid-19` = html(""),
    today = html("total<br>to date"),
    yesterday = html("since<br>yesterday"),
    `week ago` = html("since a<br>week ago")
  ) %>% 
  cols_align(align = "right") %>% 
  cols_align(align = "left", columns = c(1)) %>% 
  tab_source_note(source_note =  md("Source: Multiple tables from [Connecticut Open Data](https://data.ct.gov/stories/s/COVID-19-data/wa3g-tfvc/)")) %>% 
    tab_footnote(
    footnote = paste0('Nursing home data are reported only weekly so the dates for "today" and a "week ago" are ', format(recent_nursing_date,"%m/%d/%Y"), " and ", format(nursing_previous_date,"%m/%d/%Y"), "."),
    locations = cells_body(
      columns = vars(`Connecticut Covid-19`),
      rows = 7)
  ) %>% 
  cols_width(
    starts_with("Conn") ~ px(200),
    TRUE ~ px(130)
  ) %>%
  # tab_options(
  #   table.width = pct(100)
  # ) %>% 
  tab_options(row.striping.include_table_body = FALSE)

# issue about css and gt table 
# https://github.com/rstudio/gt/issues/547

  # tab_options(row.striping.include_table_body = FALSE)

```

